// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwrxjdamamvqbmwcjpja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cnhqZGFtYW12cWJtd2NqcGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDExMjMsImV4cCI6MjA2NzgxNzEyM30.bYXJ6WQ0AMuq6welWwCOFqcFMT0Q3V25D6hDMTOTNMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});