# SwiftLint Configuration for Dispatch

parent_config: .swiftlint.airbnb.yml

# Paths to include
included:
  - Dispatch
  - DispatchTests

# Paths to exclude
excluded:
  - Dispatch.xcodeproj
  - DispatchUITests
  - Dispatch/Assets.xcassets
  - .build
  - DerivedData

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

# Rule configurations
force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

nesting:
  type_level: 3
  function_level: 3

vertical_whitespace:
  max_empty_lines: 2

# Custom rules for architecture enforcement
custom_rules:
  # Prevent model-based navigation (causes crashes on ModelContext.reset())
  # Use AppRoute with UUID instead: NavigationLink(value: AppRoute.listing(listing.id))
  navigation_model_in_path:
    name: "Model-Based Navigation"
    regex: '(NavigationLink|ListRowLink)\s*\(\s*value\s*:\s*(?!AppRoute\b)[A-Z][a-zA-Z]*(?:\s*\)|\s*,)'
    message: "Use AppRoute with UUID instead of model types in navigation. Example: NavigationLink(value: AppRoute.listing(listing.id))"
    severity: warning
    match_kinds:
      - identifier
      - typeidentifier

  # Prevent synchronous mutations in Binding setters (causes SwiftUI runtime warnings)
  # Wrap dispatch() or appState mutations in Task { @MainActor in ... }
  #
  # NOTE: This regex has limitations with nested braces (e.g., closures within the setter).
  # The pattern `[^}]*` cannot match balanced braces, so complex setters may not be detected.
  # For definitive checking, the shell script `scripts/check_binding_patterns.sh` uses
  # Perl recursive regex which properly handles nested structures.
  # This SwiftLint rule serves as advisory first-line defense during development.
  binding_sync_mutation:
    name: "Binding Synchronous Mutation"
    regex: 'set:\s*\{[^}]*(?:dispatch\s*\(|appState\.)[^}]*\}'
    message: "Binding setter contains synchronous dispatch() or appState mutation. Wrap in Task { @MainActor in ... } to avoid 'Publishing changes from within view updates' warnings."
    severity: warning
    match_kinds:
      - identifier
      - argument
