#!/bin/bash
#
# Setup script for Dispatch environment variables
# Run: ./scripts/setup_env.sh
#
# This script:
# 1. Adds Supabase credentials to ~/.zshrc (if not already present)
# 2. Generates Secrets.swift for the app to compile
#

set -e

ZSHRC="$HOME/.zshrc"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SECRETS_FILE="$PROJECT_ROOT/Dispatch/App/Configuration/Secrets.swift"

# Default credentials (used if env vars not set)
DEFAULT_SUPABASE_URL="https://uhkrvxlclflgevocqtkh.supabase.co"
DEFAULT_SUPABASE_ANON_KEY="sb_publishable_RPjCcEeqvKdGnVWzBHjP0A_P3C9pCZO"

# Resolve credentials: prefer env vars, fall back to defaults
RESOLVED_URL="${SUPABASE_URL:-$DEFAULT_SUPABASE_URL}"
RESOLVED_KEY="${SUPABASE_ANON_KEY:-$DEFAULT_SUPABASE_ANON_KEY}"

# --- Part 1: Update ~/.zshrc ---

if grep -q "SUPABASE_URL" "$ZSHRC" 2>/dev/null; then
    echo "Info: Supabase environment variables already exist in $ZSHRC (skipping)"
else
    cat >> "$ZSHRC" << EOF

# Dispatch - Supabase credentials
export SUPABASE_URL="$DEFAULT_SUPABASE_URL"
export SUPABASE_ANON_KEY="$DEFAULT_SUPABASE_ANON_KEY"
EOF
    echo "Added Supabase environment variables to $ZSHRC"
fi

# --- Part 2: Generate Secrets.swift ---

generate_secrets() {
    cat << EOF
//
//  Secrets.swift
//  Dispatch
//
//  Auto-generated by scripts/setup_env.sh
//  DO NOT COMMIT - this file is in .gitignore
//

import Foundation

enum Secrets {
    static let supabaseURL = "$RESOLVED_URL"
    static let supabaseAnonKey = "$RESOLVED_KEY"
}
EOF
}

# Backup existing Secrets.swift if it exists and differs from what we'd generate
if [ -f "$SECRETS_FILE" ]; then
    NEW_CONTENT=$(generate_secrets)
    EXISTING_CONTENT=$(cat "$SECRETS_FILE")

    if [ "$NEW_CONTENT" != "$EXISTING_CONTENT" ]; then
        BACKUP_FILE="$SECRETS_FILE.backup.$(date +%Y%m%d_%H%M%S)"
        cp "$SECRETS_FILE" "$BACKUP_FILE"
        echo "Backed up existing Secrets.swift to $(basename "$BACKUP_FILE")"
    fi
fi

# Write Secrets.swift
generate_secrets > "$SECRETS_FILE"
echo "Generated Secrets.swift at Dispatch/App/Configuration/Secrets.swift"

# --- Summary ---

echo ""
echo "Setup complete!"
echo ""
if ! grep -q "SUPABASE_URL" "$ZSHRC" 2>/dev/null || [ -z "$SUPABASE_URL" ]; then
    echo "To apply environment variables now, run:"
    echo "    source ~/.zshrc"
    echo ""
fi
echo "Secrets.swift is ready - the app can now build."
